development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production_schedule_development
  pool: 10
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production_schedule_test
  pool: 10
  username: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production_schedule_development
  pool: 10  
  username: root