development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production_schedule_development
  pool: 10
  username: root
  password:
  #socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production_schedule_test
  pool: 10
  username: root
  password:
  #socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production_schedule_production
  pool: 10  
  username: root
  password:
  #socket: /var/run/mysqld/mysqld.sock

